In [1]:
cd editGAN

[Errno 2] No such file or directory: 'editGAN'
/home/scut/wuwanqing/editGAN


In [ ]:
python train_encoder.py --exp experiments/encoder_car.json

In [2]:
!python create_pics.py -pic_num=1 -sema_inx=4

Traceback (most recent call last):
  File "create_pics.py", line 139, in <module>
    creatPics(opt)
  File "create_pics.py", line 65, in creatPics
    G = legacy.load_network_pkl(f)['G_ema'].to(device)
  File "/home/scut/anaconda3/envs/editGAN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/home/scut/anaconda3/envs/editGAN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/scut/anaconda3/envs/editGAN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/scut/anaconda3/envs/editGAN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/scut/anaconda3/envs/editGAN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/home/scut/anaconda3/envs/editG

In [ ]:
!python create_pics_min.py

In [36]:
!python heatMapMean.py -pic_num=500 -sema_inx=4 -special_channel=True

  0%|                                                   | 0/500 [00:00<?, ?it/s]Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
100%|█████████████████████████████████████████| 500/500 [03:06<00:00,  2.69it/s]


In [7]:
!python create_pic_plus.py -pic_num=200 -sema_inx=5

  0%|                                                   | 0/200 [00:00<?, ?it/s]Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
100%|█████████████████████████████████████████| 200/200 [00:16<00:00, 11.86it/s]


In [40]:
!python create_pic_plus_sample.py

Setting up PyTorch plugin "bias_act_plugin"... Done.
 make_mean_latent 
100%|█████████████████████████████████████████████| 1/1 [00:00<00:00,  4.13it/s]


In [3]:
!python embed-project.py --steps=600 --num_steps=500 --exp experiments/encoder_cloth.json --resume ../../hdd/wanqing/editGAN/model_encoder/cloth_batch_8_loss_sampling_train_stylegan2ada/checkpoint/BEST_loss2.5923986434936523.pth --testing_path ../../hdd/wanqing/editGAN/sketch/tmp --latent_sv_folder ../../hdd/wanqing/editGAN/sketch_embed

00000000000cuda_home: /usr/local/cuda-11.1
Opt {'exp_dir': '../../hdd/wanqing/editGAN/model_encoder/cloth_batch_8_loss_sampling_train_stylegan2ada', 'category': 'car', 'im_size': [256, 256], 'n_latent': 14, 'lr': 3e-05, 'debug': False, 'bs': 8, 'sample_bs': 2, 'avg_latent': '', 'stylegan_checkpoint': 'cloth-v2-620t-s-test.pkl', 'max_label': 7, 'classfier_checkpoint': '', 'training_data_path': '../data/cloth', 'label_data_path': '', 'testing_data_path': '', 'sampling_training': True, 'use_w': False, 'same_view_code': False, 'truncation': False, 'normalize': True, 'stylegan_ver': '3', 'train_real_start_epochs': 5, 'dim': 4992, 'loss_dict': {'p_loss': 10, 'mse_loss': 1, 'encoder_loss': 5, 'e_label_ce_loss': 1, 'e_label_dice_loss': 1}, 'use_noise': False, 'noise_loss_weight': 100}
Loading networks from "cloth-v2-620t-s-test.pkl"...
Setting up PyTorch plugin "bias_act_plugin"... Done.
 make_mean_latent 
Setting up Perceptual loss...
Loading model from: /home/scut/wuwanqing/editGAN/lpips/wei

In [7]:
!pip install requests

  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
  Using cached urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
  Using cached idna-3.4-py3-none-any.whl (61 kB)


In [6]:
!python sample_pics.py

Loading networks...
Setting up PyTorch plugin "bias_act_plugin"... Done.
 make_mean_latent 
100%|███████████████████████████████████████| 5000/5000 [02:13<00:00, 37.51it/s]


In [13]:
!python stylemix.py -latents_path='../../hdd/wanqing/editGAN/latent_S'  -source_pic_id=1116 -targets=241 -styles=14-19

styles [14, 15, 16, 17, 18, 19]
Setting up PyTorch plugin "bias_act_plugin"... Done.
 make_mean_latent 
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
100%|█████████████████████████████████████████████| 1/1 [00:00<00:00, 14.20it/s]


In [8]:
!python stylemix.py -latents_path='../../hdd/wanqing/editGAN/latent_S' -sample_pic=True -source_pic_id=1944 -targets=6,7,9 -styles=7-19 -output_path='../../workspace/wanqing/editGANresult/rebuttal/stylemix'

styles [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
00000000000cuda_home: /usr/local/cuda-11.1
Setting up PyTorch plugin "bias_act_plugin"... Done.
 make_mean_latent 
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
100%|█████████████████████████████████████████████| 3/3 [00:00<00:00, 30.17it/s]


In [6]:
!python stylemix_test.py -latents_path='../../hdd/wanqing/editGAN/latent_S' -sample_pic=True -source_pic_id=3715 -targets=241 -styles=0-6

styles [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Setting up PyTorch plugin "bias_act_plugin"... Done.
 make_mean_latent 
source from sample
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
100%|█████████████████████████████████████████████| 1/1 [00:00<00:00, 60.80it/s]


In [4]:
!python test.py

Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
inputs[0][0][0] tensor(0.9909, device='cuda:0')
inputs[0][0][0] tensor(0.9909, device='cuda:0')
inputshape[0][0][0] tensor(1., device='cuda:0')


In [11]:
!python fm_mix.py -sample_pic=True -th=150 -source_pic_ids=650,2457,558 -targets=1007,1006,1040,1018 -res_mix=128 -styles=7-19 -use_sketch=True -output_path='../../hdd/wanqing/editGAN/paper_result_pic'

styles [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
00000000000cuda_home: /usr/local/cuda-11.1
Setting up PyTorch plugin "bias_act_plugin"... Done.
 make_mean_latent 
100%|█████████████████████████████████████████████| 3/3 [00:02<00:00,  1.14it/s]


In [6]:
!python fm_mix.py  -sample_pic=True -th=220 -source_pic_ids=1063,6343,5801,882,1712  -targets=1007 -res_mix=64 -styles=7-19 -use_sketch=True -output_path='../../workspace/wanqing/editGANresult/rebuttal/fm_mix'

styles [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
00000000000cuda_home: /usr/local/cuda-11.1
Setting up PyTorch plugin "bias_act_plugin"... Done.
 make_mean_latent 
100%|█████████████████████████████████████████████| 5/5 [00:01<00:00,  3.09it/s]


In [20]:
!python fm_mix.py  -sample_pic=True -th=220 -source_pic_ids=1063,6343,5801,882,1712  -targets=1007 -res_mix=64 -styles=7-19 -use_sketch=True -output_path='../../workspace/wanqing/editGANresult/rebuttal/fm_mix_wo stylemix'

styles [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
00000000000cuda_home: /usr/local/cuda-11.1
Setting up PyTorch plugin "bias_act_plugin"... Done.
 make_mean_latent 
100%|█████████████████████████████████████████████| 5/5 [00:01<00:00,  3.25it/s]


In [ ]:
!python fm_mix.py  -sample_pic=True -th=220 -source_pic_ids=1063,6343,5801,882,1712  -targets=1003 -res_mix=64 -styles=7-19 -use_sketch=True -output_path='/home/scut/workspace/wanqing/editGANresult/rebuttal/fm_mix_wo_stylemix_2024'

In [6]:
!python fm_mix.py  -th=220 \
    -source_pic_ids=5003-5004  -targets=1003,1007,1008 \
        -res_mix=64 -styles=7-19 -use_sketch=True \
            -output_path='/home/scut/workspace/wanqing/editGANresult/fm_mix_stylemix_deltaEdit'

styles [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
00000000000cuda_home: /usr/local/cuda-11.1
Setting up PyTorch plugin "bias_act_plugin"... Done.
 make_mean_latent 
  0%|                                                     | 0/3 [00:00<?, ?it/s]sketch_mask [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
orig_mask [[55 55 55 ... 55 55 55]
 [55 55 55 ... 55 55 55]
 [55 55 55 ... 55 55 55]
 ...
 [55 55 55 ... 55 55 55]
 [55 55 55 ... 55 55 55]
 [55 55 55 ... 55 55 55]]
mix_pic.shape torch.Size([1, 3, 256, 256])
sketch_mask [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
orig_mask [[55 55 55 ... 55 55 55]
 [55 55 55 ... 55 55 55]
 [55 55 55 ... 55 55 55]
 ...
 [55 55 55 ... 55 55 55]
 [55 55 55 ... 55 55 55]
 [55 55 55 ... 55 55 55]]
mix_pic.shape torch.Size([1, 3, 256, 256])
sketch_mask [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 

In [12]:
!python stylemix.py -latents_path='/home/scut/hdd/wanqing/editGAN/latent_S'  -sample_target=True -source_pic_id=1007 -targets=1063,6343,5801,882,1712 -styles=7-19 -output_path='/home/scut/workspace/wanqing/editGANresult/rebuttal/stylemix_2'

styles [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
00000000000cuda_home: /usr/local/cuda-11.1
Setting up PyTorch plugin "bias_act_plugin"... Done.
 make_mean_latent 
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
100%|█████████████████████████████████████████████| 5/5 [00:00<00:00, 29.74it/s]


In [1]:
!nvidia-smi

Thu Feb 23 14:57:35 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.108.03   Driver Version: 510.108.03   CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| 31%   46C    P8    33W / 350W |      1MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [5]:
!pip install opencv-python ninja scikit-image click

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.1/108.1 kB 646.3 kB/s eta 0:00:00 kB/s eta 0:00:01


In [2]:
!nvcc -V

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0


In [4]:
pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Note: you may need to restart the kernel to use updated packages.


In [2]:
!pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.8/94.8 kB 1.3 MB/s eta 0:00:0031m936.3 kB/s eta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 8.1 MB/s eta 0:00:008.1 MB/s eta 0:00:01
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 747.5/747.5 kB 10.6 MB/s eta 0:00:000:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.8/15.8 MB 10.1 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 10.0 MB/s eta 0:00:0031m9.4 MB/s eta 0:00:01m
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 32.3/32.3 MB 10.0 MB/s eta 0:00:00m eta 0:00:010:00:01
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.2/27.2 MB 7.9 MB/s eta 0:00:00m eta 0:00:010:00:01m
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 